brew install ack
brew install aircrack-ng
brew install apr
brew install apr-util
brew install autoconf
brew install automake
brew install axel
brew install bash
brew install bfg
brew install binutils
brew install binwalk
brew install boost
brew install boost-build
brew install boost-python
brew install brew-cask-completion
brew install bsponmpi
brew install calc
brew install chkrootkit
brew install cifer
brew install cmake
brew install colordiff
brew install coreutils
brew install cowsay
brew install cscope
brew install dark-mode
brew install dex2jar
brew install diffutils
brew install dirmngr
brew install dmd
brew install dns2tcp
brew install double-conversion
brew install doxygen
brew install ed
brew install emacs
brew install exif
brew install exiftool
brew install exiv2
brew install fcrackzip
brew install fdupes
brew install ffmpeg
brew install fftw
brew install file-formula
brew install findutils
brew install fish
brew install folly
brew install foremost
brew install freetype
brew install gawk
brew install gcc
brew install gdb
brew install gdbm
brew install geoip
brew install gettext
brew install gflags
brew install git
brew install git-lfs
brew install glog
brew install gmp
brew install gnu-indent
brew install gnu-sed
brew install gnu-tar
brew install gnu-which
brew install gnupg
brew install gnupg2
brew install gnutls
brew install gpatch
brew install gpg-agent
brew install graphicsmagick
brew install grep
brew install gsl
brew install gzip
brew install hashpump
brew install hh
brew install htop
brew install hydra
brew install icu4c
brew install imagemagick
brew install isl
brew install isl@0.14
brew install jam
brew install jasper
brew install jemalloc
brew install john
brew install jpeg
brew install knock
brew install ksh
brew install lame
brew install less
brew install libassuan
brew install libdnet
brew install libevent
brew install libexif
brew install libffi
brew install libgcrypt
brew install libgit2
brew install libgpg-error
brew install libidn
brew install libksba
brew install libmagic
brew install libmpc
brew install libpng
brew install libssh2
brew install libtasn1
brew install libtiff
brew install libtool
brew install libunistring
brew install libusb
brew install libusb-compat
brew install libxml2
brew install lua
brew install lynx
brew install lz4
brew install lzip
brew install m4
brew install macvim
brew install make
brew install makedepend
brew install mbedtls
brew install metashell
brew install mongodb
brew install moreutils
brew install mpfr
brew install mycli
brew install mysql
brew install nano
brew install narwhal
brew install ncdu
brew install ncurses
brew install netpbm
brew install nettle
brew install nmap
brew install node
brew install open-mpi
brew install openssh
brew install openssl
brew install optipng
brew install p11-kit
brew install p7zip
brew install pcre
brew install pcre2
brew install perl
brew install php56
brew install pigz
brew install pinentry
brew install pkg-config
brew install pngcheck
brew install popt
brew install pth
brew install pv
brew install python
brew install python3
brew install readline
brew install rename
brew install rhino
brew install ringojs
brew install rsync
brew install scala
brew install screen
brew install sfnt2woff
brew install sfnt2woff-zopfli
brew install snappy
brew install socat
brew install spark
brew install speedtest_cli
brew install sqlite
brew install sqlmap
brew install ssdeep
brew install ssh-copy-id
brew install subversion
brew install tcpflow
brew install tcpreplay
brew install tcptrace
brew install testssl
brew install texi2html
brew install tmux
brew install tree
brew install ucspi-tcp
brew install unixodbc
brew install unzip
brew install vbindiff
brew install vim
brew install watch
brew install wdiff
brew install webkit2png
brew install webp
brew install wget
brew install woff2
brew install x264
brew install xrootd
brew install xvid
brew install xz
brew install yasm
brew install zopfli
brew install zsh
brew install zsh-completions
